<?php

namespace App\Http\Controllers;

use Illuminate\View\View;

/**
 * P6 QR viewer (v1 view_qrcode.php).
 *
 * Like the P5 public self-service pages, v1 view_qrcode.php has no session
 * check — grantees look up their own QR at the payout venue — so this stays a
 * public top-level route. The page is static: the search / municipality /
 * verify calls go to the shared P5 `grantee-search` endpoints
 * (GranteeSearchController), which mirror v1 search_grantee.php. The QR is
 * generated by the same external service v1 used (api.qrserver.com) for parity
 * — no package added. Per C3-E the QR payload is the client's opaque
 * `qr_token` (resolved token-first by the P4 scanners since C3-D); the legacy
 * full_name fallback for legacy printed QRs is preserved in ScanService.
 */
class QrController extends Controller
{
    public function show(): View
    {
        return view('qr.viewer');
    }
}
